# Generated by Django 5.2 on 2025-04-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ridebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='carbon_saved',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ridebooking',
            name='distance_km',
            field=models.FloatField(max_length=100),
        ),
    ]
