# Generated by Django 5.2 on 2025-04-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_carbon_saved_ride_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridebooking',
            name='distance_km',
            field=models.FloatField(),
        ),
    ]
