# Generated by Django 5.2 on 2025-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_ridebooking_distance_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridebooking',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
