# Generated by Django 5.2 on 2025-04-05 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_badge'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rides', models.IntegerField(default=0)),
                ('total_km', models.FloatField(default=0)),
                ('tokens', models.IntegerField(default=0)),
                ('co2_saved', models.FloatField(default=0)),
                ('badges', models.ManyToManyField(blank=True, to='rewards.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
